### ISSUE TITLE
Fuzzing

### ISSUE THREAD

**Issue by Mindavi** [stevemarple/MicroNMEA#10]
Hey, I was looking at your repository and it seemed like a good case for some fuzzing. I found some issues that you might want to address. Test cases are built using the test_MicroNMEA binary and American Fuzzy Lop. Hope this helps improving your work :).

[crashes.zip](https://github.com/stevemarple/MicroNMEA/files/3785614/crashes.zip)

**Comment by stevemarple** [comment]
Thanks. The issues raised are fixed in 720ae62274ed4a967e143d1b73f8668ddd8df633.
