### ISSUE TITLE
MicroNMEA doesn't handle CRLF line endings

### ISSUE THREAD

**Issue by CBielstein** [stevemarple/MicroNMEA#15]
When calling `MicroNMEA::process(char)`, I have to omit part of the CRLF line ending sent by my NMEA GPS device to avoid resetting the buffer completely. If I do send the full CRLF, `process` returns false, and calls to functions such as `getSentence` return an empty string.

From reading through the code, I believe this is due to [this logic in the `process` method](https://github.com/stevemarple/MicroNMEA/blob/9e03908346164b00fde76062b866622cca559195/src/MicroNMEA.cpp#L228), which null-terminates the buffer and resets the pointer on any null, <CR>, or <LF> characters. So CRLF will invoke that code twice, resulting in the pointer equal to the start of the buffer and `_buffer[0] == \0`;

**Comment by CBielstein** [comment]
I'd be happy to submit a PR for this, if that'd be welcome. Let me know. :)

Thanks for writing and sharing this library, by the way! I enjoy the simplicity and light-weight nature of it for my tinkering.

**Comment by stevemarple** [comment]
The intention is that `MicroNMEA::process(char)` is fed a continuous stream of characters and it performs end-of-line detection itself. `process()` will return true to indicate when EOL has been detected, which signals when it is valid to retrieve information from the `MicroNMEA` object. For more information please see https://micronmea.readthedocs.io/en/latest/

It sounds like you are trying to handle EOL detection externally to the library when you should be checking the return value from `process()`. There are callback functions to help support more advanced usage and to enable custom decoding of uncommon NMEA sentences.

**Comment by CBielstein** [comment]
Thanks for the quick response! What you're saying makes sense. I've been using SoftwareSerial's `readString()` method to get a full NMEA message and then feed that to `process()`. As you point out, that means my code is handling EOL outside of the library. Perhaps this is just me being an Arduino newbie and writing inefficient code. 😅

For my understanding, is the logic here that MicroNMEA shouldn't detect a valid message on both CR and LF at the end of NMEA messages because that would likely result in the caller identifying two distinct messages received?

Let me go update my code to follow the correct pattern. I'll comment back if I'm still convinced there's an issue here...but it is really sounding like the bug is in my own code. Apologies for the false report!

**Comment by stevemarple** [comment]
By using `readString()` you'll be using an extra buffer, hence consuming extra memory. Use SoftwareSerial's `available()` function to check there is data to read, and then use `read()` instead, passing a character at a time to `MicroNMEA::process(char)`.

> For my understanding, is the logic here that MicroNMEA shouldn't detect a valid message on both CR and LF at the end of NMEA messages because that would likely result in the caller identifying two distinct messages received?

Different operating systems have [different conventions](https://en.wikipedia.org/wiki/Newline#Representation) for line endings and `MicroNMEA` is designed to handle the various common cases. CRLF will result in `MicroNMEA` sensing two lines, but the second will be empty and ignored. That is why it is imperative that you check the return value from `process()`.

**Comment by stevemarple** [comment]
Have you resolved this issue? Can it be closed now?

**Comment by stevemarple** [comment]
I believe the error was due to calling the library incorrectly. No further response so closing this issue.

**Comment by CBielstein** [comment]
Apologies for the (very) slow response. Busy weeks around the end of November and I didn't get a chance to try it out until recently. It was indeed an issue in how I was calling the library. Thanks again for the tips on how to correct it!
