### ISSUE TITLE
HDOP in GGA message is not stored correctly

### ISSUE THREAD

**Issue by nabelekt** [stevemarple/MicroNMEA#16]
https://github.com/stevemarple/MicroNMEA/blob/9e03908346164b00fde76062b866622cca559195/src/MicroNMEA.h#L313 declares `_hdop` as a `uint8_t`, but it is a float value. See page 148 of https://www.u-blox.com/en/docs/UBX-13003221 (may need to save it locally to view it correctly).

Ex.:
```
$GNGGA,020144.00,3932.86607,N,10306.30428,W,1,04,4.72,1711.6,M,-21.7,M,,*45
```
The `4.72` is the HDOP value.

**Comment by stevemarple** [comment]
HDOP is stored internally, and reported to the user, in tenths. This is described in the function [documentation](https://github.com/stevemarple/MicroNMEA/blob/9e03908346164b00fde76062b866622cca559195/src/MicroNMEA.h#L103) for the `getHDOP()` function.

`4.72` will be stored as reported as `47` tenths (representing `4.7`). I don't believe that the loss of precision in HDOP in such cases is important, particularly in a library whose aim is to be compact.

**Comment by nabelekt** [comment]
Got it. I think that's consistent with what I was seeing. Do you know the range of values that HDOP can have? Are they within
[0, 25.5] -> [0, 255] ?

**Comment by nabelekt** [comment]
I am still trying to find the limits of HDOP values, but https://www.gpsworld.com/gnss-systemalgorithms-methodsinnovation-improving-dilution-precision-9100/ mentions a value of 26.335. If that is a possibility, then the `uint8_t` used here would _not_ be sufficient to store the `uint8_t(26.335*10) = 263` value.

**Comment by stevemarple** [comment]
The latest commits (see version 2.0.6) test and protect against arithmetic overflow, and unwanted negative values. (The git comment about underflow is incorrect). This might mean rare cases (eg HDOP > 25.5, or number of satellites > 255) fail to store the correct value and instead are assigned the value 25.5 or 255.

(I don't think we are in a situation yet where the number of satellites is going to exceed 255 but even if that is reached who cares if there are more than 255? A satisfactory position or timing result does not need that many satellites in view).

Can this issue be closed now?

**Comment by nabelekt** [comment]
Yes, thanks for the update!

**Comment by nabelekt** [comment]
For what it's worth, and for anyone else looking for this information: before any satellites are acquired, u-blox M8 GNSS modules report the HDOP value as 99.99.
