### ISSUE TITLE
What is the unit of speed

### ISSUE THREAD

**Issue by Loongle** [stevemarple/MicroNMEA#18]
Hi! I get the data from actual driving, the results puzzled me. The output speed of 30km/h is about 12000, the output speed of 40km/h is about 16000, and the output speed of 50km/h is about 20000.

Can you tell me what the units of speed are?

**Comment by svdrummer** [comment]
Try tinyGPS++ i think this lib may be dead

**Comment by stevemarple** [comment]
Units will depend on how your GPS is configured.
