### ISSUE TITLE
MemoryFree.h

### ISSUE THREAD

**Issue by audstanley** [stevemarple/MicroNMEA#2]
is Not included, can you put a link in your README.md?

**Comment by stevemarple** [comment]
The library is available from https://github.com/maniacbug/MemoryFree
a9827d94b29e9bbcc9f7f7c6deb4fea163659fca removes the dependency on MemoryFree and documents in the example code where it can be obtained from.

**Comment by audstanley** [comment]
@stevemarple Thanks.
