### ISSUE TITLE
Obtaining/calculating velocity vectors by NMEA protocol

### ISSUE THREAD

**Issue by brightproject** [stevemarple/MicroNMEA#20]
Good day @stevemarple
For one project I need to get vectors/directions of velocities to the north, east and down.
The action takes place in the `NED` [coordinate](https://en.wikipedia.org/wiki/Local_tangent_plane_coordinates) system.
The `UBX` protocol and of course the device itself somehow produces this data.
I have a `GPS/GLONASS` receiver `GN02D`.
It provides data only via the `NMEA` protocol.
![gps-nmea-0183_img01](https://github.com/stevemarple/MicroNMEA/assets/1788098/5775c33a-6709-41df-9b99-ba3e44fcf430)

I can get `VTG` data - speed and heading over ground.
![VTG_NMEA](https://github.com/stevemarple/MicroNMEA/assets/1788098/07075c3e-31b5-4d08-b702-25bdd29986d1)

My real data from module
`$GNVTG,7.00,T,7.00,M,0.000,N,0.000,K,A*3D`
For some reason, the `VTG` only issues `GNSS`, but does not issue `GPS`... perhaps because I conduct experiments in an apartment, and not in the open air.

Is it possible to somehow obtain the NED velocity vectors from these data?
![NED_velocity](https://github.com/stevemarple/MicroNMEA/assets/1788098/00bb0865-4102-45e2-ac8c-bdb7d681f022)
P.S.
It is also interesting how to get time in week format from the `NMEA` protocol, `iTOW` as it is in the `UBX` protocol.
![iTOW](https://github.com/stevemarple/MicroNMEA/assets/1788098/05f5c296-7acd-43eb-b437-f973dda004cd)
I would be grateful to the community for help.

**Comment by stevemarple** [comment]
This is not an issue with MicroNMEA, it is a call for general help.
