### ISSUE TITLE
Cannot get correct parsing of GPS+GLONASS data

### ISSUE THREAD

**Issue by stamasd** [stevemarple/MicroNMEA#7]
I am trying to build a GPS+GLONASS receiver based on a GNSS dual module, and I have come across MicroNMEA. Since I use an Arduino Nano with it I had to modify the example demo to use SoftwareSerial for the GNSS module, and also use pin 2 for the PPS interrupt (which I connected to the module's PPS output). The module I'm using has a PPS LED so I know I have a fix. However the console output says I don't have a fix. I can provide samples of the module's raw output as well as serial console output and the modified sketch. Unfortunately it doesn't seem like I can attach a sketch or even a text file to github's issue tracker. The module doesn't have a reset input so I just ignored A0 and the reset mechanism.

**Comment by stevemarple** [comment]
Please post the console output so we can see what MicroNMEA thinks has been sent. Some samples of the raw output would be useful - I will add them to `extras/test/nmea_sentences.txt` and ensure they can be parsed correctly by the library, both now and in future after any changes have been made. The code can be run on a PC which removes any possible timing issues that may be occurring from using SoftwareSerial.

**Comment by stamasd** [comment]
Here is the raw output from the module via serial (edited out a few digits from the location):
$GNRMC,132637.00,A,4113.xxxxx,N,07315.xxxxx,W,0.630,,100119,,,A*70
$GNVTG,,T,,M,0.630,N,1.167,K,A*39
$GNGGA,132637.00,4113.xxxxx,N,07315.xxxxx,W,1,05,2.78,59.0,M,-34.2,M,,*4D
$GNGSA,A,3,15,20,13,,,,,,,,,,3.92,2.78,2.76*1E
$GNGSA,A,3,85,79,,,,,,,,,,,3.92,2.78,2.76*19
$GPGSV,2,1,07,05,15,093,20,13,40,049,29,15,77,044,28,20,38,296,24*78
$GPGSV,2,2,07,24,36,152,22,27,08,324,,29,12,204,16*4A
$GLGSV,3,1,10,68,00,068,,69,42,042,,70,54,303,,71,13,265,*6A
$GLGSV,3,2,10,78,14,030,,79,26,082,19,80,12,134,,84,31,193,*6C
$GLGSV,3,3,10,85,56,272,28,86,19,331,22*60
$GNGLL,4113.xxxxx,N,07315.xxxxx,W,132637.00,A,A*64

And here is the output from the demo sketch via console (both while a fix was achieved):
$GLGSV,3,2,09,79,27,079,25,80,14,132,,84,28,193,,85,56,266,*63Valid fix: no
Nav. system: none
Num. satellites: 0
HDOP: 25.5
Date/time: 0-0-0T99:99:99
Latitude (deg): 999.000000
Longitude (deg): 999.000000
Altitude (m): not available
Speed: -2147483.750
Course: -2147483.750
-----------------------
$GNRMC,133159.00,A,4113.xxxxx,N,07315.xxxxx,W,0.228,,100119,,,AW,1,07,1.27,-7.6,M,-34.2,M,,*50Unknown sentence: $GLGSV,3,2,09,79,27,079,25,80,14,132,,84,28,193,,85,56,266,*63$GNRMC,133159.00,A,4113.xxxxx,N,07315

$GNGSA,A,3,15,20,24,13,,,,,,,,,2.45,1.27,2.09*12Unknown sentence: $GNGSA,A,3,15,20,24,13,,,,,,,,,2.45,1.27,2.09*12

$GNGSA,A,3,64,38,151,21,27,09,323,14,29,10,203,*45
$GLGSV,3,19,79,27,079,23,80,14,132,,84,28,193,,85,56,266,*65
$GLGSV,3,3,09,86,21,330,21*52Unknown sentence: $GLGSV,3,3,09,86,21,330,21*52

$GNGLL,4113.xxxxx,N,07315.xxxxxW,133159.00,A,A*62
Valid fix: no
Nav. system: none
Num. satellites: 0
HDOP: 25.5
Date/time: 0-0-0T99:99:99
Latitude (deg): 999.000000
Longitude (deg): 999.000000
Altitude (m): not available
Speed: -2147483.750
Course: -2147483.750
-----------------------
$GNRMC,133200.00,A,4113.xxxxx,N,07315.xxxxx,W,0.186,,100119,,,A7,1.27,-6.7,M,-34.2,M,,*52
$GNGSA,A,3,15,20,24,13,,,,,,,,,2.45,1.27,2.09*12Unknown sentence: $GNGSA,A,3,15,20,24,13,,,,,,,,,2.45,1.27,2.09*12

$GNGSA,A,3,6,79,78,,,,,,,,,,2.45,1.27,2.09*1E
$GPGSV,2,1,07,024,38,151,20,27,09,323,17,29,10,203,*47
$GLGSV,3,1,09,69,39,045,28,70,55,309,22,71,15,268,,78,12,028,32*64Unknown sentence: $GLGSV,3,1,09,69,39,045,28,70,55,309,22,71,15,268,,78,12,028,32*64

$GLGSV,3,2,09,79,27,079,21,80,14,132,,84,28,193,23,85,56,266,*Valid fix: no
Nav. system: none
Num. satellites: 0
HDOP: 25.5
Date/time: 0-0-0T99:99:99
Latitude (deg): 999.000000
Longitude (deg): 999.000000
Altitude (m): not available
Speed: -2147483.750
Course: -2147483.750
-----------------------
$GNRMC,133201.00,A,4113.xxxxx,N,07315.xxxxx,W,0.045,,100119,,,A6,W,1,07,1.27,-6.3,M,-34.2,M,,*58
$GNGSA,A,3,15,20,24,13,,,,,,,,,2.45,1.27,2.09*12Unknown sentence: $GNGSA,A,3,15,20,24,13,,,,,,,,,2.45,1.27,2.09*12

$GNGSA,A,3,6,79,78,,,,,,,,,,2.45,1.27,2.09*1E
$GPGSV,2,1,07,024,38,151,20,27,09,323,16,29,10,203,16*41
$GLGSV,3,1,09,69,39,045,28,70,55,309,,71,15,268,,78,12,028,32*64Unknown sentence: $GLGSV,3,1,09,69,39,045,28,70,55,309,,71,15,268,,78,12,028,32*64

$GLGSV,3,2,09,79,27,079,19,80,14,132,,84,28,193,25,85,56,266,*
Valid fix: no
Nav. system: none
Num. satellites: 0
HDOP: 25.5
Date/time: 0-0-0T99:99:99
Latitude (deg): 999.000000
Longitude (deg): 999.000000
Altitude (m): not available
Speed: -2147483.750
Course: -2147483.750
-----------------------
$GNRMC,133202.00,A,4113.xxxxx,N,07315.xxxxx,W,0.159,,100119,,,A6,1.33,-5.7,M,-34.2,M,,*5A
$GNGSA,A,3,15,20,24,,,,,,,,,,2.52,1.33,2.14*1FUnknown sentence: $GNGSA,A,3,15,20,24,,,,,,,,,,2.52,1.33,2.14*1F

$GNGSA,A,3,69,9,78,,,,,,,,,,2.52,1.33,2.14*11
$GPGSV,2,1,07,024,38,151,21,27,09,323,17,29,10,203,14*43
$GLGSV,3,1,09,69,39,045,28,70,55,309,,71,15,268,,78,12,028,32*64Unknown sentence: $GLGSV,3,1,09,69,39,045,28,70,55,309,,71,15,268,,78,12,028,32*64

**Comment by stamasd** [comment]
The github issue tracker is acting weird, it won't let me attach files at all, and the formatting came out weird. I also can't edit what I already posted. let me know if you can work with the info above or need more info. You can get the text files directly from my dropbox https://www.dropbox.com/s/jah46524vq4gef8/serial%20raw%20output%20edited.txt?dl=0 and https://www.dropbox.com/s/q9lxfg62mlq0wwq/micromnea%20output%20edited.txt?dl=0 These were captures directly from the serial console.

**Comment by stevemarple** [comment]
To minimise memory requirements only two types of messages are parsed, `$GPGGA` (and its GNSS versions `$GNGGA`, `$GLGGA`, and `$GAGGA`) and `$GPRMC` (and its GNSS versions `$GNRMC`, `$GLRMC`, and `$GARMC`). During each reporting period both types of message should be output by the GPS receiver. To minimise the workload on `SoftwareSerial` you can configure the GPS receiver to stop outputting other types of message. For the NV08C receiver I use I first send the command `$PORZB` to clear all messages, then I send the command ` $PORZB,RMC,1,GGA,1` to send the RMC and GGA messages once a second. You may need to adjust those commands to suit your receiver.
